AgentClassName: GradientDoubleDQN
NeuralNetClassName: QnetLnShallow
batch_size: 256
beta: 0.0001
buffer_size: 10000
corruption_mode: none
corruption_ratio: 0.0
delta_improvement: 8
env_name: junction_400
env_step_duration: 6
epsilon_final: 0.01
epsilon_initial: 1.0
epsilon_scheduler_name: get_epsilon_dynamic
gamma: 0.98
hidden_dims:
- 256
- 48
imputation_mode: none
length_per_cell: 5
lr_final: 0.0001
lr_initial: 0.001
lr_scheduler_name: LRSchedulerDynamic
max_green: 60
max_num_epochs: 10
min_green: 6
minimum_size: 1000
num_episodes: 50
num_parallel_envs: 20
num_test_episodes: 20
plot_figure: false
render_mode: rgb_array
reward_type: waiting_time
run_mode: test
save_path: agent.pth
speed_threshold: 0.3
target_update: 10
time_limit: 3600
verbose: true
yellow: 3
